repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T02_DOROTHY-JOHNSON
repo_name: 2025-2_T02_DOROTHY-JOHNSON


site_name: Dorothy Johnson

nav:
   - Home: index.md

theme:
   name: material 
   palette:
    - scheme: default
      toggle: 
         icon: material/toggle-switch-off-outline
         name: Dark mode
      primary: blue
    - scheme: slate
      toggle:
         icon: material/toggle-switch
         name: Light mode
      primary: blue